---
- hosts: db
  become: true
  tasks:
    - name: Install Docker
      apt: { name: [docker.io, python3-pip], state: present, update_cache: true }
    - pip: { name: docker }
    - service: { name: docker, state: started, enabled: true }
    - community.docker.docker_container:
        name: posts-db
        image: rmitdominichynes/sdo-2025:db
        restart_policy: always
        published_ports: ["5432:5432"]
        env:
          POSTGRES_DB: posts
          POSTGRES_USER: posts
          POSTGRES_PASSWORD: posts

- hosts: backend
  become: true
  tasks:
    - name: Install Docker
      apt: { name: [docker.io, python3-pip], state: present, update_cache: true }
    - pip: { name: docker }
    - service: { name: docker, state: started, enabled: true }
    - community.docker.docker_container:
        name: posts-backend
        image: rmitdominichynes/sdo-2025:backend
        restart_policy: always
        published_ports: ["80:3000"]
        env:
          DB_HOST: "{{ db_host }}"
          DB_USER: posts
          DB_PASSWORD: posts
          DB_NAME: posts

- hosts: frontend
  become: true
  tasks:
    - name: Install Docker
      apt: { name: [docker.io, python3-pip], state: present, update_cache: true }
    - pip: { name: docker }
    - service: { name: docker, state: started, enabled: true }
    - community.docker.docker_container:
        name: posts-frontend
        image: rmitdominichynes/sdo-2025:frontend
        restart_policy: always
        published_ports: ["8081:80"]
        env:
          REACT_APP_API_URL: "http://{{ backend_host }}"
